package io.github.aedev.flow.ui.components.videoplayer.sheet

import android.app.Application
import android.content.Context
import androidx.activity.ComponentActivity
import androidx.compose.material3.MaterialTheme
import androidx.compose.ui.test.assertIsDisplayed
import androidx.compose.ui.test.hasScrollToIndexAction
import androidx.compose.ui.test.junit4.createAndroidComposeRule
import androidx.compose.ui.test.onNodeWithText
import androidx.compose.ui.test.performClick
import androidx.compose.ui.test.performMouseInput
import androidx.compose.ui.test.performTouchInput
import androidx.compose.ui.test.swipeUp
import androidx.compose.ui.unit.dp
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.google.common.truth.Truth.assertThat
import io.github.aedev.flow.R
import io.github.aedev.flow.data.transcript.TranscriptCue
import io.github.aedev.flow.player.state.SubtitleOption
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.annotation.Config

/**
 * The transcript's reading contract: playback follows the reader, not the other way round, and the
 * pill is the only thing that hands the list back to the clock.
 */
@RunWith(AndroidJUnit4::class)
@Config(sdk = [34], application = Application::class, qualifiers = "w411dp-h891dp")
class FlowTranscriptBottomSheetTest {
    @get:Rule
    val rule = createAndroidComposeRule<ComponentActivity>()

    private val context: Context
        get() = ApplicationProvider.getApplicationContext()

    private val cues =
        List(40) { index ->
            TranscriptCue(startMs = index * 5_000L, text = "Line $index", durationMs = 5_000L)
        }

    private val english =
        SubtitleOption(url = "https://captions/en", language = "en", label = "English", isAutoGenerated = false)
    private val german =
        SubtitleOption(
            url = "https://captions/de",
            language = "de",
            label = "German",
            isAutoGenerated = false,
            isTranslated = true,
        )

    private fun setSheet(
        positionMs: Long = 60_000L,
        chapters: List<TranscriptChapter> = emptyList(),
        tracks: List<SubtitleOption> = emptyList(),
        selectedTrackUrl: String? = null,
        onTrackSelected: (String) -> Unit = {},
        onSeekMs: (Long) -> Unit = {},
    ) {
        rule.setContent {
            MaterialTheme {
                FlowTranscriptBottomSheet(
                    cues = cues,
                    isLoading = false,
                    currentPositionMs = { positionMs },
                    artworkUrl = null,
                    onSeekMs = onSeekMs,
                    onDismiss = {},
                    chapters = chapters,
                    tracks = tracks,
                    selectedTrackUrl = selectedTrackUrl,
                    onTrackSelected = onTrackSelected,
                    expandedHeight = 400.dp,
                )
            }
        }
        rule.waitForIdle()
    }

    private fun syncPill() = rule.onNodeWithText(context.getString(R.string.transcript_resync))

    @Test
    fun theFollowsOwnScrollDoesNotRaiseTheSyncPill() {
        setSheet()

        syncPill().assertDoesNotExist()
    }

    @Test
    fun draggingRaisesTheSyncPillAndTappingItGoesBack() {
        setSheet()

        rule.onNodeWithText("Line 10", substring = true).performTouchInput { swipeUp() }
        rule.waitForIdle()

        syncPill().assertIsDisplayed()

        syncPill().performClick()
        rule.waitForIdle()

        syncPill().assertDoesNotExist()
    }

    @Test
    fun aMouseWheelAlsoRaisesTheSyncPill() {
        setSheet()

        // The search field is single-line and so carries a horizontal scroll action of its own;
        // only the transcript list can be scrolled to an index.
        rule.onNode(hasScrollToIndexAction()).performMouseInput {
            moveTo(center)
            scroll(6f)
        }
        rule.waitForIdle()

        syncPill().assertExists()
    }

    @Test
    fun tappingALineSeeksToIt() {
        var seekedTo: Long? = null
        setSheet(onSeekMs = { seekedTo = it })

        rule.onNodeWithText("Line 11", substring = true).performClick()

        assertThat(seekedTo).isEqualTo(55_000L)
    }

    @Test
    fun chapterHeadingsSitAboveTheirLines() {
        setSheet(
            positionMs = 0L,
            chapters = listOf(TranscriptChapter(startMs = 0L, title = "Full system specs")),
        )

        rule.onNodeWithText("Full system specs").assertIsDisplayed()
    }

    @Test
    fun aSingleTrackShowsNoLanguageMenu() {
        setSheet(tracks = listOf(english), selectedTrackUrl = english.url)

        rule.onNodeWithText(english.label).assertDoesNotExist()
    }

    @Test
    fun theLanguageMenuReportsTheTrackItPicked() {
        var picked: String? = null
        setSheet(
            tracks = listOf(english, german),
            selectedTrackUrl = english.url,
            onTrackSelected = { picked = it },
        )

        rule.onNodeWithText(english.label).performClick()
        rule.waitForIdle()

        val translated =
            context.getString(
                R.string.subtitle_auto_generated_template,
                german.label,
                context.getString(R.string.subtitle_translated),
            )
        rule.onNodeWithText(translated).performClick()
        rule.waitForIdle()

        assertThat(picked).isEqualTo(german.url)
    }
}
