package io.github.aedev.flow.ui.screens.player.state

import com.google.common.truth.Truth.assertThat
import io.github.aedev.flow.player.state.SubtitleOption
import org.junit.Test

private fun option(
    language: String,
    isAutoGenerated: Boolean = false,
    isTranslated: Boolean = false,
) = SubtitleOption(
    url = "https://example.test/$language${if (isTranslated) "&tlang=$language" else ""}",
    language = language,
    label = language,
    isAutoGenerated = isAutoGenerated,
    isTranslated = isTranslated,
)

class SubtitleFollowsAudioTest {
    private val subtitles = listOf(option("en"), option("es"), option("ja", isAutoGenerated = true))

    @Test
    fun `switching audio moves a visible subtitle to the same language`() {
        val index =
            SubtitleSelection.subtitleFollowingAudio(subtitles, audioLanguage = "es", selectedUrl = subtitles[0].url)

        assertThat(index).isEqualTo(1)
    }

    @Test
    fun `subtitles stay off when they were off`() {
        val index = SubtitleSelection.subtitleFollowingAudio(subtitles, audioLanguage = "es", selectedUrl = null)

        assertThat(index).isNull()
    }

    @Test
    fun `no move when the chosen language is already showing`() {
        val index =
            SubtitleSelection.subtitleFollowingAudio(subtitles, audioLanguage = "es", selectedUrl = subtitles[1].url)

        assertThat(index).isNull()
    }

    @Test
    fun `no move when the audio language has no caption track`() {
        val index =
            SubtitleSelection.subtitleFollowingAudio(subtitles, audioLanguage = "pt", selectedUrl = subtitles[0].url)

        assertThat(index).isNull()
    }

    @Test
    fun `a regional audio tag matches the base caption language`() {
        val index =
            SubtitleSelection.subtitleFollowingAudio(subtitles, audioLanguage = "es-419", selectedUrl = subtitles[0].url)

        assertThat(index).isEqualTo(1)
    }

    @Test
    fun `an auto-generated track is still used when it is the only one in that language`() {
        val index =
            SubtitleSelection.subtitleFollowingAudio(subtitles, audioLanguage = "ja", selectedUrl = subtitles[0].url)

        assertThat(index).isEqualTo(2)
    }

    @Test
    fun `a blank audio language moves nothing`() {
        val index = SubtitleSelection.subtitleFollowingAudio(subtitles, audioLanguage = "", selectedUrl = subtitles[0].url)

        assertThat(index).isNull()
    }
}

class SubtitleFallbackTest {
    @Test
    fun `an authored track that fails has no fallback`() {
        val subtitles = listOf(option("en"), option("fr"))

        val fallback =
            SubtitleSelection.fallbackIndexFor(subtitles, failedIndex = 0, failedLanguage = "en", wasTranslated = false)

        assertThat(fallback).isNull()
    }

    @Test
    fun `a failed translation prefers the same language authored track`() {
        val subtitles = listOf(option("en"), option("es"), option("es", isTranslated = true))

        val fallback =
            SubtitleSelection.fallbackIndexFor(subtitles, failedIndex = 2, failedLanguage = "es", wasTranslated = true)

        assertThat(fallback).isEqualTo(1)
    }

    @Test
    fun `a failed translation falls back to an authored track in another language`() {
        val subtitles = listOf(option("en"), option("ja", isTranslated = true))

        val fallback =
            SubtitleSelection.fallbackIndexFor(subtitles, failedIndex = 1, failedLanguage = "ja", wasTranslated = true)

        assertThat(fallback).isEqualTo(0)
    }

    @Test
    fun `an auto-generated track is used only when nothing authored remains`() {
        val subtitles = listOf(option("en", isAutoGenerated = true), option("ja", isTranslated = true))

        val fallback =
            SubtitleSelection.fallbackIndexFor(subtitles, failedIndex = 1, failedLanguage = "ja", wasTranslated = true)

        assertThat(fallback).isEqualTo(0)
    }

    @Test
    fun `a translation is never the fallback for another translation`() {
        val subtitles = listOf(option("fr", isTranslated = true), option("ja", isTranslated = true))

        val fallback =
            SubtitleSelection.fallbackIndexFor(subtitles, failedIndex = 1, failedLanguage = "ja", wasTranslated = true)

        assertThat(fallback).isNull()
    }

    @Test
    fun `the failed track is never its own fallback`() {
        val subtitles = listOf(option("ja", isTranslated = true))

        val fallback =
            SubtitleSelection.fallbackIndexFor(subtitles, failedIndex = 0, failedLanguage = "ja", wasTranslated = true)

        assertThat(fallback).isNull()
    }
}
