package io.github.aedev.flow.player.stream

import android.util.Log
import io.github.aedev.flow.innertube.models.response.PlayerResponse
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import java.util.Locale

object CaptionTrackResolver {
    private const val TAG = "CaptionTrackResolver"

    /** Marks a track produced by YouTube's machine translation of another caption track. */
    const val TRANSLATED_PARAM = "tlang"

    const val NO_PREFERRED_LANGUAGE = "none"

    /**
     * @param format timedtext format requested for authored tracks. Defaults to
     *   [MediaFormat.TRANSCRIPT3] (srv3), YouTube's own styled/positioned caption XML, decoded by
     *   [io.github.aedev.flow.player.renderer.subtitle.Srv3SubtitleParser]. Callers that need the
     *   plain-text `vtt` conversion (offline downloads validate and store the raw response body)
     *   pass [MediaFormat.VTT] explicitly. Auto-generated (ASR) tracks always stay on `vtt`
     *   regardless: their srv3 form is a roll-up stream of word-timed segments, which the rolling
     *   caption renderer does not reconstruct.
     * @param translateTo a BCP-47 tag to machine-translate into when the video carries no track in
     *   that language. Only one is produced: the response offers up to 156 translation languages,
     *   and materialising them all would bury the authored tracks in the picker.
     */
    fun resolve(
        playerResponse: PlayerResponse,
        format: MediaFormat = MediaFormat.TRANSCRIPT3,
        translateTo: String? = null,
    ): List<SubtitlesStream> = resolveTracklist(playerResponse.captions?.playerCaptionsTracklistRenderer, format, translateTo)

    fun resolveTracklist(
        renderer: PlayerResponse.Captions.PlayerCaptionsTracklistRenderer?,
        format: MediaFormat = MediaFormat.TRANSCRIPT3,
        translateTo: String? = null,
    ): List<SubtitlesStream> {
        if (renderer == null) return emptyList()
        val tracks =
            renderer.captionTracks
                ?.filter { !it.baseUrl.isNullOrBlank() && !it.languageCode.isNullOrBlank() }
                .orEmpty()
        if (tracks.isEmpty()) return emptyList()

        val result =
            tracks.mapNotNull { track ->
                val autoGenerated = track.kind == "asr"
                buildStream(
                    track.baseUrl!!,
                    track.languageCode!!,
                    autoGenerated = autoGenerated,
                    format = if (autoGenerated) MediaFormat.VTT else format,
                )
            }

        val translated = translatedTrack(renderer, tracks, result, translateTo, format)
        Log.d(TAG, "Resolved ${result.size} caption tracks from InnerTube captions (translated=${translated != null})")
        return if (translated == null) result else result + translated
    }

    private fun translatedTrack(
        renderer: PlayerResponse.Captions.PlayerCaptionsTracklistRenderer,
        tracks: List<PlayerResponse.Captions.CaptionTrack>,
        resolved: List<SubtitlesStream>,
        translateTo: String?,
        format: MediaFormat,
    ): SubtitlesStream? {
        val wanted = translateTo?.takeIf { it.isNotBlank() && it != NO_PREFERRED_LANGUAGE } ?: return null
        val offered =
            renderer.translationLanguages
                ?.mapNotNull { it.languageCode }
                ?.firstOrNull { baseLanguage(it) == baseLanguage(wanted) }
                ?: return null
        val alreadyCovered =
            bestMatch(
                candidates = resolved,
                languageTag = offered,
                tagOf = { it.languageTag },
                isAutoGenerated = { it.isAutoGenerated },
            ) != null
        if (alreadyCovered) return null

        // Authored source first: a translation of a transcript reads better than a translation of
        // speech recognition, and an ASR source also forces the plain-text vtt form.
        val source =
            tracks.firstOrNull { it.isTranslatable == true && it.kind != "asr" }
                ?: tracks.firstOrNull { it.isTranslatable == true }
                ?: return null
        val sourceIsAsr = source.kind == "asr"
        val url = timedTextUrl(source.baseUrl!!, if (sourceIsAsr) MediaFormat.VTT else format)
        return buildStream(
            baseUrl = "$url&$TRANSLATED_PARAM=$offered",
            languageCode = offered,
            autoGenerated = true,
            format = if (sourceIsAsr) MediaFormat.VTT else format,
            alreadyFormatted = true,
        )
    }

    fun isTranslated(stream: SubtitlesStream): Boolean = stream.getContent().contains("&$TRANSLATED_PARAM=")

    private fun buildStream(
        baseUrl: String,
        languageCode: String,
        autoGenerated: Boolean,
        format: MediaFormat,
        alreadyFormatted: Boolean = false,
    ): SubtitlesStream? =
        try {
            SubtitlesStream
                .Builder()
                .setContent(if (alreadyFormatted) baseUrl else timedTextUrl(baseUrl, format), true)
                .setMediaFormat(format)
                .setLanguageCode(languageCode)
                .setAutoGenerated(autoGenerated)
                .build()
        } catch (e: Exception) {
            Log.w(TAG, "Failed to build SubtitlesStream for $languageCode: ${e.message}")
            null
        }

    private fun timedTextUrl(
        baseUrl: String,
        format: MediaFormat,
    ): String {
        val separatorIndex = baseUrl.indexOf('?')
        val path = if (separatorIndex >= 0) baseUrl.substring(0, separatorIndex) else baseUrl
        val query = if (separatorIndex >= 0) baseUrl.substring(separatorIndex + 1) else ""

        val retained =
            query
                .split('&')
                .filter { it.isNotEmpty() && !it.isParam("fmt") && !it.isParam(TRANSLATED_PARAM) }
                .toMutableList()

        retained.add("fmt=${format.fmtQueryValue()}")

        return "$path?${retained.joinToString("&")}"
    }

    private fun MediaFormat.fmtQueryValue(): String =
        when (this) {
            MediaFormat.TRANSCRIPT3 -> "srv3"
            MediaFormat.VTT -> "vtt"
            else -> throw IllegalArgumentException("Unsupported timedtext format: $this")
        }

    private fun String.isParam(name: String): Boolean = startsWith("$name=", ignoreCase = true) || equals(name, ignoreCase = true)

    fun <T> bestMatch(
        candidates: List<T>,
        languageTag: String?,
        tagOf: (T) -> String?,
        isAutoGenerated: (T) -> Boolean,
    ): T? {
        val wanted = languageTag?.takeIf { it.isNotBlank() && it != NO_PREFERRED_LANGUAGE } ?: return null
        val wantedBase = baseLanguage(wanted)
        val ranked =
            candidates
                .filter { baseLanguage(tagOf(it).orEmpty()) == wantedBase }
                .sortedWith(
                    compareBy<T> { !tagOf(it).equals(wanted, ignoreCase = true) }
                        .thenBy { isAutoGenerated(it) },
                )
        return ranked.firstOrNull()
    }

    private fun baseLanguage(tag: String): String =
        tag
            .substringBefore('-')
            .substringBefore('_')
            .lowercase(Locale.ROOT)
}
